npm install @syncfusion/ej2-angular-buttons --legacy-peer-deps
npm install @syncfusion/ej2-angular-calendars --legacy-peer-deps
npm install @syncfusion/ej2-angular-inputs --legacy-peer-deps
npm install @syncfusion/ej2-angular-kanban --legacy-peer-deps
npm install @syncfusion/ej2-angular-schedule --legacy-peer-deps
npm install @syncfusion/ej2-angular-dropdowns --legacy-peer-deps
npm install @syncfusion/ej2-angular-charts --legacy-peer-deps
npm install @syncfusion/ej2-angular-lists --legacy-peer-deps
npm install @syncfusion/ej2-angular-navigations --legacy-peer-deps
npm install @syncfusion/ej2-angular-circulargauge --legacy-peer-deps
npm install @syncfusion/ej2-angular-grids --legacy-peer-deps
npm install @syncfusion/ej2-angular-popups --legacy-peer-deps
npm install @syncfusion/ej2-angular-maps --legacy-peer-deps
npm install @syncfusion/ej2-angular-splitbuttons --legacy-peer-deps
npm install @syncfusion/ej2-angular-documenteditor --legacy-peer-deps
npm install @syncfusion/ej2-compression --legacy-peer-deps
npm install @syncfusion/ej2-data --legacy-peer-deps
npm install @syncfusion/ej2-file-utils --legacy-peer-deps
npm install @syncfusion/ej2-angular-notifications --legacy-peer-deps
npm install @syncfusion/ej2-angular-richtexteditor --legacy-peer-deps
npm install @syncfusion/ej2-angular-filemanager --legacy-peer-deps
