ng update @syncfusion/ej2-angular-buttons@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-calendars@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-inputs@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-kanban@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-schedule@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-dropdowns@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-charts@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-lists@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-navigations@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-circulargauge@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-grids@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-popups@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-maps@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-splitbuttons@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-documenteditor@latest --force --allow-dirty
ng update @syncfusion/ej2-compression@latest --force --allow-dirty
ng update @syncfusion/ej2-data@latest --force --allow-dirty
ng update @syncfusion/ej2-file-utils@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-notifications@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-richtexteditor@latest --force --allow-dirty
ng update @syncfusion/ej2-angular-filemanager@latest --force --allow-dirty
